<?php 
    $file = $block->getFileByWebsiteId(); 
    $websiteId = $block->getWebsiteId();
    $blockLocation = $block->getLayout()->createBlock('Amasty\Storelocator\Block\Location');
?>

<a href="<?php echo $block->getMediaBaseUrl($file->getFile()); ?>" class="show-catalog <?php echo $block->getData('class'); ?>" target="_blank">
    <img src="<?php echo $block->getMediaBaseUrl($block->getData('image')); ?>" alt="">
</a>

<script type="text/javascript">
    require(['jquery', 'domReady!'], function($) {
        <?php if($websiteId == 1) { ?>
            $('.show-catalog').click(function(e){
                e.preventDefault();
                e.stopImmediatePropagation();
                $('#store-selector-popup').show();
                $('#store-selector-popup .popup-content h2').text('LOCATE YOUR STORE TO VIEW THE CATALOG');
                localStorage.setItem("catalog", true); 
                
                return false;
            });
        <?php } else { ?>
            if(localStorage.getItem("catalog") == 'true') {
                localStorage.setItem("catalog", false); 
                $('.show-catalog').attr('target', '_self').attr('download', '').get(0).click();
            } 
                
        <?php } ?>
    });
</script>

