<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<?php /** @var \Amasty\MegaMenu\Block\Head $block */ ?>

<style>
    .ammenu-nav-sections.-hamburger,
    .ammenu-menu-wrapper.-desktop,
    .ammenu-menu-wrapper.-hamburger-top,
    .ammenu-nav-sections .ammenu-title,
    .ammenu-main-container .ambrands-popup-filter {
        background: <?= $block->escapeHtml($block->getColorStyle('menu_background'))?> !important;
    }

    .ammenu-nav-sections .ammenu-title.active {
        background: <?= $block->escapeHtml($block->getColorStyle('submenu_background'))?> !important;
    }

    .ammenu-menu-wrapper.-desktop .ammenu-item.-main > .ammenu-link,
    .ammenu-menu-wrapper.-hamburger-top .ammenu-item.-main .ammenu-link,
    .ammenu-nav-sections .ammenu-title > .ammenu-link {
        color: <?= $block->escapeHtml($block->getColorStyle('menu_text'))?> !important;
    }

    .ammenu-menu-wrapper.-desktop .ammenu-submenu-container .ammenu-link,
    .ammenu-menu-wrapper.-desktop .ammenu-submenu-container,
    .ammenu-menu-wrapper.-desktop .ammenu-product-list .product-item-info *:not(.-nocolor):not(.swatch-option),
    .ammenu-menu-wrapper.-hamburger-top .ammenu-submenu-container,
    .ammenu-nav-sections.-hamburger .ammenu-submenu-container,
    .ammenu-menu-wrapper.-mobile .ammenu-link,
    .ammenu-nav-sections .ammenu-tabs-container > .ammenu-content,
    .ammenu-nav-sections .header.links li > a {
        color: <?= $block->escapeHtml($block->getColorStyle('submenu_text'))?> !important;
    }

    .ammenu-main-container:not(.swatch-option, .ammenu-menu-header) {
        color: <?= $block->escapeHtml($block->getColorStyle('submenu_text'))?> !important;
    }

    .ammenu-nav-sections.-accordion .ammenu-icon:focus:before,
    .ammenu-nav-sections.-accordion .ammenu-icon:focus:after,
    .ammenu-menu-wrapper.-mobile .ammenu-icon:focus:before,
    .ammenu-menu-wrapper.-mobile .ammenu-icom:focus:after {
        background-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .nav-sections:not(.-drill) .ammenu-submenu[aria-selected="true"] ~ .ammenu-toggle .ammenu-icon:after,
    .nav-sections:not(.-drill) .ammenu-submenu[aria-selected="true"] ~ .ammenu-toggle .ammenu-icon:before {
        background-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .nav-sections:not(.-drill) .ammenu-submenu[aria-selected='true'] ~ .ammenu-link {
        color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-menu-wrapper.-desktop .ammenu-item.-main:hover > .ammenu-link {
        color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-items .current,
    .ammenu-nav-sections .ammenu-items .ammenu-link.current,
    .ammenu-menu-wrapper .ammenu-items .ammenu-item.current > .ammenu-link,
    .ammenu-items .current > .ammenu-wrapper {
        color: <?= $block->escapeHtml($block->getColorStyle('menu_highlight'))?> !important;
    }

    .ammenu-nav-sections.-accordion:not(.-hamburger) .ammenu-items .current > .ammenu-wrapper {
        color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-menu-wrapper.-desktop .ammenu-submenu-container,
    .ammenu-menu-wrapper.-desktop.ammenu-item.-main:hover,
    .ammenu-menu-wrapper.-desktop .ammenu-link:not(.-level1) + .ammenu-item.-child,
    .ammenu-menu-wrapper.-hamburger-top .ammenu-submenu-container,
    .ammenu-nav-sections .ammenu-content,
    .ammenu-menu-wrapper.-mobile .ammenu-submenu,
    .ammenu-menu-wrapper.-mobile .ammenu-link.-main,
    .ammenu-main-container .brand-images .brands-letter .letter .title,
    .ammenu-nav-sections:not(.-hamburger) .ammenu-item.-drill-opened {
        background-color: <?= $block->escapeHtml($block->getColorStyle('submenu_background'))?> !important;
    }

    .ammenu-nav-sections.-hamburger:not(.-drill) .ammenu-submenu-container {
        background: <?= $block->escapeHtml($block->getColorStyle('menu_background'))?> !important;
    }

    .-drill-opened .ammenu-toggle .ammenu-icon:not(.-small),
    .-drill-opened .ammenu-toggle .ammenu-icon:before,
    .-drill-opened .ammenu-toggle .ammenu-icon:after,
    .-drill-opened > .ammenu-arrow {
        background: <?= $block->escapeHtml($block->getColorStyle('menu_text'))?> !important;
    }

    .ammenu-nav-sections .ammenu-link,
    .ammenu-nav-sections .ammenu-link.-main,
    .ammenu-nav-sections .ammenu-menu-header{
        color: <?= $block->escapeHtml($block->getColorStyle('menu_text'))?> !important;
    }

    .ammenu-menu-wrapper .ammenu-icon:after,
    .ammenu-menu-wrapper .ammenu-icon:before,
    .ammenu-menu-wrapper .ammenu-icon.-small.-down:before,
    .ammenu-menu-wrapper .ammenu-submenu.-collapsed + .ammenu-toggle .ammenu-icon:before,
    .ammenu-menu-wrapper  .ammenu-arrow:before,
    .ammenu-menu-wrapper  .ammenu-arrow:after {
        background: <?= $block->escapeHtml($block->getColorStyle('menu_text'))?> !important;
    }

    <?php $backgroundImage = $block->getSubmenuBackgroundImage();?>
    <?php if ($backgroundImage): ?>
    .ammenu-menu-wrapper.-desktop .ammenu-submenu-container,
    .ammenu-menu-wrapper.-hamburger-top .ammenu-submenu-container {
        background-image: url(<?= $block->escapeHtml($backgroundImage); ?> )!important;
    }
    <?php endif;?>

    .ammenu-main-container .ambrands-list-popup {
    <?php $color = $block->colourBrightness($block->getColorStyle('submenu_background'), .9); ?>
        background: <?= $block->escapeHtml($color) ?> !important;
    }

    .ammenu-main-container .ambrands-popup-filter .ambrands-letter.-disabled {
    <?php $color = $block->colourBrightness($block->getColorStyle('submenu_background'), .8); ?>
        background: <?= $block->escapeHtml($color) ?> !important;
    }

    .ammenu-menu-wrapper.-desktop .ammenu-link:hover > .ammenu-wrapper,
    .ammenu-menu-wrapper.-desktop .ammenu-link.-hovered > .ammenu-wrapper,
    .ammenu-menu-wrapper.-mobile .ammenu-link.-level2:hover,
    .ammenu-menu-wrapper.-hamburger-top .ammenu-item:hover .ammenu-link,
    .ammenu-nav-sections.-accordion .ammenu-item:hover > .ammenu-link,
    .ammenu-nav-sections.-hamburger .ammenu-link:hover .ammenu-wrapper {
        color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-menu-welcome,
    .ammenu-menu-wrapper.-desktop .ammenu-main-container .ammenu-link.-level1:hover:before,
    .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow,
    .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow:before,
    .ammenu-menu-wrapper.-desktop .ammenu-categories-container .ammenu-arrow:after {
        background: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
        border-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-menu-wrapper.-hamburger .ammenu-wrapper a:hover {
        border-color: <?= $block->escapeHtml($block->getColorStyle('category_hover_color'))?> !important;
    }

    .ammenu-menu-toggle .ammenu-icon {
        border-color: <?= $block->escapeHtml($block->getColorStyle('toggle_icon_color'))?> !important;
    }

    .ammenu-menu-close-btn {
        color: <?= $block->escapeHtml($block->getColorStyle('toggle_icon_color'))?> !important;
    }

    .ammenu-nav-sections.-hamburger .ammenu-menu-welcome .message{
        color: <?= $block->escapeHtml($block->getColorStyle('menu_background'))?> !important;
    }
</style>
