<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <div class="actions dropdown options switcher-options">
            <?php 
                $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
                $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
                $storeID       = $storeManager->getStore()->getStoreId(); 
                $storeName     = $storeManager->getStore()->getName();
            ?>
           <a href="#" class="header-select-store">Your store is : <span class="selected"><?php echo $storeName; ?></span></a>
        </div>
    </div>
<?php else: ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language">
        <div class="actions dropdown options switcher-options">
           <a href="#" class="header-select-store">Please select your store.</a>
        </div>
    </div>
<?php endif; ?>
