<?php
  $block= $block->getLayout()->createBlock('Amasty\StoreLocator\Block\Location');
?>
<div id="store-selector-popup">
  <div class="bg-overlay"></div>
  <div class="popup-content">
    <h2>LOCATE YOUR STORE TO VIEW PRICES</h2>
    <p>Enter your postcode and find your nearest Furniture One showroom for localised recommended retail prices</p>
    <form>
      <input type="number" id="postcode" name="postcode" placeholder="enter postcode" />
      <div class="search-result">

      </div>
      <button class="f1-button" type="button" id="select-store" disabled="disabled">Show prices</button>
    </form>
  </div>
</div>
<script type="text/javascript">
  require(['jquery', 'domReady!','https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
            $block->configProvider->getApiKey()
        ); ?>'], function($) {
    $('.show-price-link').click(function(){
      $('#store-selector-popup').show();
      return false;
    });
    $('#store-selector-popup .bg-overlay').click(function(){
      $('#store-selector-popup').hide();
    });

    $('#postcode').on('input', function(){
      var geocoder = new google.maps.Geocoder();
      if($(this).val().length > 3) {
        var lat = '';
        var lng = '';
        var address = $(this).val();
        geocoder.geocode({'address': address, componentRestrictions: {country: 'AU'}}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            lat = results[0].geometry.location.lat();
            lng = results[0].geometry.location.lng();
            params = {
              lat: lat,
              lng: lng,
              sortByDistance: 1
            };
            $.ajax({
                url: 'amlocator/index/ajax/',
                type: 'POST',
                data: params,
                showLoader: true
            }).done($.proxy(function (response) {
                response = JSON.parse(response);
                $('.search-result').empty();
                var html = "";
                var i = 0;
                $.each(response.items, function(key, value) {
                  if(i !== 5) {
                    html = html + '<div class="result-store" data-store="'+ value.url_key +'"><p>'+ value.name +' - ' + value.zip +'</p></div>';
                  }
                  i = parseInt(i) + parseInt(1);
                });
                $('.search-result').html(html);
            }));
          } else {
            alert("Geocode was not successful for the following reason: " + status);
          }
        });
      }
    });

    $(document).on('click', ".result-store", function() {
      $('.result-store').removeClass('active');
      $(this).toggleClass('active');
      $('#select-store').prop("disabled", false).attr('data-post', '{"action":"stores/store/redirect/","data":{"___store":"'+ $(this).attr('data-store') +'","___from_store":"default"}}');
    });
  });
</script>
<a href="#" data-post='{"action":"stores/store/redirect/","data":{"___store":"default","___from_store":"default"}}'>back to default store</a>
