<?php
/**
 * @author Verdikt Team
 * @package Verdikt_Storelocator
 */
?>
<?php /** @var \Verdikt\Storelocator\Block\Location $block */ ?>

<div class="amlocator-main-container" style="<?= $block->escapeHtml($block->getMainBlockStyles()); ?>">
    <?php if ($block->getWidgetDescription()): ?>
        <div class="store-list-title">
            <h4><?= $block->escapeHtml($block->getWidgetDescription()); ?></h4>
        </div>
    <?php endif; ?>
    <div class="amlocator-map-container" id="<?= $block->escapeHtml($block->getMapContainerId()); ?>">
        <?php if ($block->getShowSearch()): ?>
            <div class="amlocator-search-container">
                <div class="amlocator-block -current amlocator-current-location">
                    <div class="amlocator-wrapper">
                        <input type="text" value="" class="amlocator-text"
                               name="address" placeholder="<?= $block->escapeHtml(__('Current location')); ?>"
                               data-amlocator-js="address"
                               autocomplete="off">
                        <span class="amlocator-search" data-amlocator-js="search"></span>
                        <span class="amlocator-reset -hidden" data-amlocator-js="reset"></span>
                    </div>
                </div>
                <div class="amlocator-block -search amlocator-search-radius">
                    <label class="amlocator-title" id="range_radius" for="radius">
                        <?= $block->escapeHtml(__('Search Radius')); ?>
                    </label>
                    <?php if ($block->getDistanceConfig() == 'choose'): ?>
                        <select class="amlocator-select -measurement" id="amlocator-measurement"
                                name="measurement" data-amlocator-js="measurment-select">
                            <option value="km"><?= $block->escapeHtml(__('km')); ?></option>
                            <option selected="selected" value="mi"><?= $block->escapeHtml(__('mi')); ?></option>
                        </select>
                    <?php else:?>
                        <label>, <?= $block->escapeHtml($block->getDistanceConfig()) ?></label>
                    <?php endif ?>
                    <div class="amlocator-wrapper">
                        <?php if ($block->getRadiusType() == 'select' || empty($block->getRadiusType())): ?>
                            <select class="amlocator-select" data-amlocator-js="radius-select" name="radius" >
                                <?php foreach ($block->getSearchRadius() as $range): ?>
                                    <option value="<?= is_numeric($range) ? (int)$range : ''; ?>">
                                        <?= $block->escapeHtml($range) ?>
                                    </option>
                                <?php endforeach;?>
                            </select>
                        <?php else:?>
                            <div class="amlocator-range-slider" data-amlocator-js="range-slider">
                                <div class="amlocator-handle ui-slider-handle">
                                    <div class="amlocator-tooltip">
                                        <span data-amlocator-js="radius-value"></span>
                                        <span data-amlocator-js="radius-measurment">
                                        <?= ($block->getDistanceConfig() != 'choose')
                                            ? $block->escapeHtml($block->getDistanceConfig())
                                            : '' ?>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="radius"
                                   data-amlocator-js="radius-select"
                                   value="<?= (int)$block->getMaxRadiusValue(); ?>"
                                   min="<?= (int)$block->getMinRadiusValue(); ?>"
                                   max="<?= (int)$block->getMaxRadiusValue(); ?>"/>
                        <?php endif ?>
                    </div>
                </div>
                <div class="amlocator-block -separator"><hr class="hr"/></div>
                <button class="amlocator-button -nearby"
                        title="<?= $block->escapeHtml(__('Locate Nearby')); ?>">
                    <?= $block->escapeHtml(__('Locate Nearby')); ?>
                </button>
                <div class="amlocator-block -separator"><hr class="hr"/></div>
            </div>
        <?php endif; ?>
        <?php if ($block->getShowLocations()): ?>
            <?php if ($attributes = $block->getAttributes()): ?>
                <div class="amlocator-block -filter">
                    <div class="amlocator-filters-container">
                        <div class="amlocator-title amlocator-attribute-filter"
                             data-amlocator-js="filters-title">
                            <span><?= $block->escapeHtml(__('Filter')); ?></span>
                            <span class="amlocator-arrow <?=
                            $block->escapeHtml($block->getFilterClass()) ? ' -down' : '';
                            ?>">
                            </span>
                        </div>
                        <div class="amlocator-content<?= $block->escapeHtml($block->getFilterClass()); ?>"
                             data-amlocator-js="filters-container">
                            <?php $attributes = $block->getAttributes();?>
                            <form class="attributes" action="#" data-amlocator-js="attributes-form">
                                <?php foreach ($attributes as $attribute): ?>
                                    <div class="amlocator-attribute-wrapper">
                                        <div class="amlocator-label"><?= $block->escapeHtml($attribute['label']); ?></div>
                                        <div class="amlocator-input">
                                            <select name="<?= (int)$attribute['attribute_id'];?>"
                                                    class="amlocator-select"
                                                <?php if ($attribute['frontend_input'] == 'multiselect'): ?>
                                                    multiple="multiple"
                                                    data-amlocator-js="multiple-select"
                                                <?php endif;?>>
                                                <?php if ($attribute['frontend_input'] != 'multiselect'):?>
                                                    <option value="" selected><?= $block->escapeHtml(__('Please Select')); ?></option>
                                                <?php endif?>
                                                <?php foreach ($attribute['options'] as $valueId => $option): ?>
                                                    <option
                                                        <?php if ($block->isOptionSelected(
                                                            $attribute,
                                                            $option
                                                        )): ?>
                                                            selected
                                                        <?php endif; ?>
                                                        value="<?= (int)$option['value'] ?>">
                                                        <?= $block->escapeHtml(
                                                            $option['label']
                                                        ); ?>
                                                    </option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </form>
                            <div class="amlocator-actions">
                                <span class="amlocator-clear"
                                   title="<?= $block->escapeHtml(__('Reset')); ?>"
                                   data-amlocator-js="clear-filters">
                                    <?= $block->escapeHtml(__('Reset')); ?>
                                </span>
                                <button class="amlocator-button amlocator-filter-attribute"
                                        title="<?= $block->escapeHtml(__('Filter')) ?>">
                                    <?= $block->escapeHtml(__('Filter')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="amlocator-block -storelist amlocator-store-list">
                <?= $block->getLeftBlockHtml(); ?>
            </div>
        <?php endif; ?>
        
    </div>
</div>


